In [ ]:
print("1D",a,b,"\n\n","2D",c,"\n\n","3D",d)

1D [1 2 3 4] [5 6 7 8] 

 2D [[1 2 3 4]
 [5 6 7 8]] 

 3D [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
# Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?
print(a+b)

[ 6  8 10 12]


In [ ]:
# Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?
print(a*2)

[2 4 6 8]


In [ ]:
# Create an identity matrix of dimension 4-by-4.
eye=ny.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Convert a 1-D array to a 3-D array.
e=ny.arange(1,28)
print(e)
e.reshape(3,3,3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
# Convert all the elements of a numpy array from float to integer datatype.
f=ny.ones((3,3,3),dtype="int")
print(f)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
# Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive).
g=ny.arange(0,105,5)
print(g)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
